import { describe, it, expect } from "vitest";
import type { PrototypeTechnicalReviewDossier } from "../types/cadastre";

describe("Phase 3.6D: Prototype Technical Review Dossier & Export Subsystem", () => {
  const mockDossier: PrototypeTechnicalReviewDossier = {
    dossier_version: "3.6D-PROTOTYPE",
    generated_at: "2026-09-06T12:00:00Z",
    prototype_notice: "Research Prototype — Not a statutory cadastral record, title certificate, ownership deed, or official government 3D ULPIN.",
    parcel: {
      id: "parcel-1",
      ulpin_2d: "ULPIN-2D-PARCEL-01",
      survey_number: "SY-102/4",
      district: "Hyderabad",
      state: "Telangana",
      village_code: "VIL-001",
      area_sqm: 1250.5,
    },
    building: {
      id: "bldg-1",
      building_code: "BLDG-TOWER-A",
      building_name: "Commercial & Residential Tower A",
      total_floors_above: 12,
      total_floors_below: 2,
    },
    unit_identity: {
      id: "unit-f01-102",
      prototype_ulpin_3d: "ULPIN-3D-F01-102",
      tier_code: "F",
      floor_code: "F01",
      unit_sequence: 3,
      unit_label: "F01-102 Residential Apartment",
      unit_type: "APARTMENT",
      status: "UNDER_REVIEW",
      identifier_notice: "The Prototype 3D Unit ID is a research identifier generated by this prototype system and is not represented as an officially adopted government 3D cadastral identifier.",
    },
    geometry_summary: {
      crs: "EPSG:32644 (WGS 84 / UTM Zone 44N)",
      srid: 32644,
      z_min: 3.5,
      z_max: 7.0,
      modeled_vertical_height_m: 3.5,
      volume_cbm: 910.76,
      surface_area_sqm: 645.2,
      face_count: 6,
      geometry_type: "PolyhedralSurface",
      is_closed: true,
      is_solid: true,
      is_within_parcel: true,
      z_terminology_note: "Z minimum and Z maximum represent prototype modeled vertical coordinates. Modeled Vertical Height (Zmax - Zmin) represents the 3D bounding prism height and is not certified clear height or structural clearance.",
    },
    taxonomy: {
      category: "UPPER_FLOORS",
      category_label: "Upper Floors (Residential / Commercial)",
      unit_class: "RESIDENTIAL_UPPER",
      unit_class_label: "Residential Storey Unit",
    },
    lifecycle: {
      current_status: "UNDER_REVIEW",
      overall_readiness: "READY_FOR_HUMAN_REVIEW",
      passed_count: 5,
      warning_count: 0,
      error_count: 0,
      readiness_items: [
        {
          code: "SOLID_WATERTIGHTNESS",
          label: "3D B-Rep Solid Geometry",
          passed: true,
          severity: "INFO",
          message: "PolyhedralSurface forms a valid closed 2-manifold solid.",
        },
        {
          code: "POSITIVE_VOLUME",
          label: "Positive Interior Volume",
          passed: true,
          severity: "INFO",
          message: "Verified positive volume of 910.76 m³.",
        },
      ],
      permitted_verification_roles: ["HUMAN_REVIEWER", "LICENSED_SURVEYOR", "REVENUE_OFFICIAL"],
      governance_notice: "Verification is strictly restricted to authorized human roles. SYSTEM_VALIDATOR and automated algorithms cannot verify units.",
    },
    source_evidence: {
      evidence_count: 2,
      evidence_records: [
        {
          id: "ev-lidar-01",
          source_type: "LIDAR_POINTCLOUD",
          dataset_name: "prototype_tower_a.las",
          file_uri: "s3://cadastre/raw/prototype_tower_a.las",
          accuracy_horizontal_m: 0.05,
          accuracy_vertical_m: 0.05,
          sensor_category: "AERIAL_LIDAR",
          is_synthetic: true,
          assessment_level: "HIGH",
          assessment_rationale: "Validated aerial point cloud with point density > 25 pts/m²",
          geometry_status: "UNAVAILABLE",
          geometry_notice: "Source geometry unavailable — metadata/provenance only.",
          sensor_capability_notice: "LiDAR evidence available to this prototype does not by itself establish underground geometry.",
          sha256_fingerprint: "a1b2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890",
          fingerprint_notice: "SHA-256 source fingerprint used for provenance and reproducibility.",
          created_at: "2026-09-01T10:00:00Z",
        },
      ],
      provenance_pipeline: [
        {
          step_number: 1,
          stage: "INGESTION",
          name: "Format & CRS Ingestion",
          status: "COMPLETED",
          details: "Validated LAS against EPSG:32644",
        },
      ],
      disclaimer: "Source evidence records represent technical ingestion metadata and lineage; they do not store persistent raw geometry columns in this prototype.",
    },
    evidence_fusion: {
      unit_id: "unit-f01-102",
      prototype_ulpin_3d: "ULPIN-3D-F01-102",
      status: "UNDER_REVIEW",
      floor_code: "F01",
      tier_code: "F",
      is_underground: false,
      overall_confidence: "MEDIUM",
      overall_confidence_label: "Medium Technical Evidence Corroboration",
      assessment_method: "MULTI_SOURCE_WEIGHTED_HEURISTIC",
      dimensions: {
        source_presence: "MULTI_SOURCE",
        source_presence_reason: "Multiple sources available",
        provenance_quality: "HIGH",
        provenance_quality_reason: "High quality provenance",
        geometry_support: "HIGH",
        geometry_support_reason: "Strong geometry support",
        vertical_support: "MEDIUM",
        vertical_support_reason: "Moderate vertical agreement",
        source_agreement: "MEDIUM",
        source_agreement_reason: "Minor differences in height",
        evidence_completeness: "HIGH",
        evidence_completeness_reason: "Complete coverage",
        underground_safety: "HIGH",
        underground_safety_reason: "Above ground unit",
      },
      sources: [],
      comparisons: [
        {
          measurement_name: "Storey Height",
          source_a_type: "LIDAR_POINTCLOUD",
          source_a_val: 3.5,
          source_b_type: "BIM_IFC",
          source_b_val: 3.62,
          difference: 0.12,
          tolerance: 0.1,
          unit_of_measure: "m",
          status: "MINOR_DISCREPANCY",
          notes: "0.12m variance between LiDAR return and BIM ceiling",
        },
      ],
      conflicts: [
        {
          code: "Z_RANGE_CONFLICT",
          severity: "WARNING",
          affected_attribute: "z_max",
          source_a: "LIDAR_POINTCLOUD",
          source_b: "BIM_IFC",
          recommendation: "Reviewer should inspect ceiling slab interface with LiDAR point cloud profile.",
        },
      ],
      reviewer_attention: [],
      underground_warnings: [],
      disclaimer: "Multi-source evidence fusion is a technical decision-support assessment and not statutory certification.",
      evaluated_at: "2026-09-06T12:00:00Z",
    },
    topology: {
      unit_id: "unit-f01-102",
      prototype_ulpin_3d: "ULPIN-3D-F01-102",
      parcel_id: "parcel-1",
      overall_quality_status: "VALID",
      solid_validation: {
        is_closed: true,
        is_solid: true,
        validity_code: "VALID_SOLID",
        volume_cbm: 910.76,
        z_min_geom: 3.5,
        z_max_geom: 7.0,
        z_min_meta: 3.5,
        z_max_meta: 7.0,
        is_valid: true,
        details: "PolyhedralSurface forms a valid closed 2-manifold solid with positive volume.",
      },
      containment: {
        unit_id: "unit-f01-102",
        prototype_ulpin_3d: "ULPIN-3D-F01-102",
        is_within_parcel: true,
        status: "CONTAINED",
        severity: "INFO",
        message: "Unit boundary is fully within parcel boundary",
      },
      vertical_continuity: {
        unit_id: "unit-f01-102",
        prototype_ulpin_3d: "ULPIN-3D-F01-102",
        floor_code: "F01",
        z_min: 3.5,
        z_max: 7.0,
        relation_to_lower_unit: "CONTIGUOUS",
        gap_or_overlap_m: 0.0,
        severity: "INFO",
        details: "Direct boundary contact with lower unit F00-COMM at Z=3.50m",
      },
      peer_relationships: [],
      conflict_count: 0,
      warning_count: 0,
      disclaimer: "Topology evaluation performed via SFCGAL 3D geometry engine.",
      audited_at: "2026-09-06T12:00:00Z",
    },
    ai_context: {
      has_analysis: true,
      advisory_notice: "AI-assisted non-authoritative advisory context. AI outputs and heuristic scores do not constitute statutory verification, cadastral proof, or ownership certainty.",
    },
    review_history: [
      {
        id: "audit-01",
        action: "INITIAL_PROPOSAL",
        previous_status: undefined,
        new_status: "PROPOSED",
        actor_role: "SYSTEM_INITIALIZER",
        timestamp: "2026-09-01T10:00:00Z",
      },
    ],
    limitations: [
      "Research Prototype: This dossier is generated by a research prototype system and does not constitute a statutory cadastral record, title certificate, or legal ownership deed.",
      "Prototype Identifier: The Prototype 3D Unit ID is an experimental spatial reference used for research and is not an officially adopted government 3D cadastral identifier.",
      "Metadata-Only Evidence: Source evidence records represent technical ingestion metadata and lineage; raw source geometries (LiDAR points, BIM meshes) are not co-persisted in this prototype.",
      "Discrepancy Spatial Non-Localization: Discrepancy notices indicate metric variances between source attributes; exact spatial fault boundaries cannot be highlighted in 3D without stored source geometry meshes.",
      "Sensor Scope & Subsurface Limits: LiDAR evidence available to this prototype does not by itself establish underground geometry. Subterranean units require independent engineering/survey review.",
      "Polyhedral Boundary Approximation: 3D solids are faceted PolyhedralSurface representations; Modeled Vertical Height represents bounding elevation interval (Zmax - Zmin) and not architectural clear height.",
      "Horizontal Footprint Containment: Parcel containment checks verify 2D polygon footprint inclusion and do not constitute a complete 3D legal air-rights or subsurface easement determination.",
      "Human Governance Requirement: AI candidate proposals and automated readiness checks are non-authoritative advisory aids. Official verification remains strictly restricted to authorized human review roles.",
    ],
  };

  it("Requirement 1 & 2: Prototype notice is prominent and explicitly disclaims statutory certification", () => {
    expect(mockDossier.prototype_notice).toContain("Research Prototype");
    expect(mockDossier.prototype_notice).toContain("Not a statutory cadastral record");
    expect(mockDossier.dossier_version).toBe("3.6D-PROTOTYPE");
  });

  it("Requirement 3: Unit identity uses Prototype 3D Unit ID terminology", () => {
    expect(mockDossier.unit_identity.prototype_ulpin_3d).toBe("ULPIN-3D-F01-102");
    expect(mockDossier.unit_identity.identifier_notice).toContain("Prototype 3D Unit ID is a research identifier");
  });

  it("Requirement 4: Modeled geometry is labeled Modeled Vertical Height (not clear height)", () => {
    expect(mockDossier.geometry_summary.modeled_vertical_height_m).toBe(3.5);
    expect(mockDossier.geometry_summary.z_terminology_note).toContain("not certified clear height");
  });

  it("Requirement 5: Source evidence records are marked metadata/provenance only", () => {
    const ev = mockDossier.source_evidence.evidence_records[0];
    expect(ev.geometry_status).toBe("UNAVAILABLE");
    expect(ev.geometry_notice).toBe("Source geometry unavailable — metadata/provenance only.");
  });

  it("Requirement 6: SHA-256 fingerprint is described strictly as provenance and reproducibility", () => {
    const ev = mockDossier.source_evidence.evidence_records[0];
    expect(ev.fingerprint_notice).toBe("SHA-256 source fingerprint used for provenance and reproducibility.");
  });

  it("Requirement 7: Evidence fusion preserves categorical confidence and decomposable dimensions", () => {
    expect(mockDossier.evidence_fusion.overall_confidence).toBe("MEDIUM");
    expect(mockDossier.evidence_fusion.overall_confidence).not.toMatch(/%/);
    expect(mockDossier.evidence_fusion.dimensions.geometry_support).toBe("HIGH");
  });

  it("Requirement 8: Discrepancy notices maintain spatial reality notice", () => {
    const conflict = mockDossier.evidence_fusion.conflicts[0];
    expect(conflict.code).toBe("Z_RANGE_CONFLICT");
    expect(conflict.severity).toBe("WARNING");
    expect(conflict.recommendation).toContain("ceiling slab interface");
  });

  it("Requirement 9: AI context is explicitly non-authoritative advisory context", () => {
    expect(mockDossier.ai_context.advisory_notice).toContain("AI-assisted non-authoritative advisory context");
    expect(mockDossier.ai_context.advisory_notice).toContain("do not constitute statutory verification");
  });

  it("Requirement 10: Human review governance restricts verification to authorized human roles", () => {
    expect(mockDossier.lifecycle.permitted_verification_roles).toContain("HUMAN_REVIEWER");
    expect(mockDossier.lifecycle.permitted_verification_roles).toContain("LICENSED_SURVEYOR");
    expect(mockDossier.lifecycle.permitted_verification_roles).not.toContain("SYSTEM_VALIDATOR");
    expect(mockDossier.lifecycle.governance_notice).toContain("SYSTEM_VALIDATOR and automated algorithms cannot verify units");
  });

  it("Requirement 11: Standardized limitations enumerate all 8 research boundaries", () => {
    expect(mockDossier.limitations.length).toBe(8);
    expect(mockDossier.limitations[0]).toContain("Research Prototype");
    expect(mockDossier.limitations[2]).toContain("Metadata-Only Evidence");
    expect(mockDossier.limitations[4]).toContain("LiDAR evidence available to this prototype does not by itself establish underground geometry");
  });
});
