"""
SIH26011: 3D ULPIN Generation & Vertical Property Mapping System
Phase 3.6D: Prototype Technical Review Dossier & Export Schemas

Data models defining the consolidated, explainable, read-only technical review dossier.
"""
from datetime import datetime
from typing import List, Dict, Any, Optional
from uuid import UUID
from pydantic import BaseModel, Field

from backend.app.schemas.responses import (
    VerticalTaxonomyClassification,
    CheckItem,
    ConflictItem,
    ProvenanceStep,
    ReviewReadinessItem,
    AuditHistoryItem,
    UnitTopologyReportResponse,
    AICandidateAnalysisResponse
)
from backend.app.schemas.evidence_fusion import (
    UnitEvidenceFusionResponse,
    EvidenceDimensionBreakdown,
    EvaluatedSourceRecord,
    AgreementComparisonItem,
    ConflictNoticeItem,
    EvidenceDimensionLevel
)


class DossierParcelContext(BaseModel):
    id: UUID
    ulpin_2d: str
    survey_number: str
    district: str
    state: str
    village_code: Optional[str] = None
    area_sqm: float


class DossierBuildingContext(BaseModel):
    id: Optional[UUID] = None
    building_code: Optional[str] = None
    building_name: Optional[str] = None
    total_floors_above: Optional[int] = None
    total_floors_below: Optional[int] = None


class DossierUnitIdentity(BaseModel):
    id: UUID
    prototype_ulpin_3d: str
    tier_code: str
    floor_code: str
    unit_sequence: int
    unit_label: str
    unit_type: str
    status: str
    identifier_notice: str = (
        "The Prototype 3D Unit ID is a research identifier generated by this prototype system "
        "and is not represented as an officially adopted government 3D cadastral identifier."
    )


class DossierGeometrySummary(BaseModel):
    crs: str = "EPSG:32644 (WGS 84 / UTM Zone 44N)"
    srid: int = 32644
    z_min: float
    z_max: float
    modeled_vertical_height_m: float
    volume_cbm: float
    surface_area_sqm: Optional[float] = None
    face_count: Optional[int] = None
    geometry_type: str = "PolyhedralSurface"
    is_closed: bool
    is_solid: bool
    is_within_parcel: bool
    z_terminology_note: str = (
        "Z minimum and Z maximum represent prototype modeled vertical coordinates. "
        "Modeled Vertical Height (Zmax - Zmin) represents the 3D bounding prism height and "
        "is not certified clear height or structural clearance."
    )


class DossierEvidenceItem(BaseModel):
    id: UUID
    source_type: str
    dataset_name: str
    file_uri: str
    accuracy_horizontal_m: Optional[float] = None
    accuracy_vertical_m: Optional[float] = None
    sensor_category: str
    is_synthetic: bool = False
    assessment_level: str
    assessment_rationale: str
    geometry_status: str = "UNAVAILABLE"
    geometry_notice: str = "Source geometry unavailable — metadata/provenance only."
    sensor_capability_notice: Optional[str] = None
    sha256_fingerprint: Optional[str] = None
    fingerprint_notice: str = "SHA-256 source fingerprint used for provenance and reproducibility."
    metadata_json: Optional[Dict[str, Any]] = None
    created_at: datetime


class DossierSourceEvidenceSection(BaseModel):
    evidence_count: int
    evidence_records: List[DossierEvidenceItem]
    provenance_pipeline: List[ProvenanceStep]
    disclaimer: str = (
        "Source evidence records represent technical ingestion metadata and lineage; "
        "they do not store persistent raw geometry columns in this prototype."
    )


class DossierLifecycleSection(BaseModel):
    current_status: str
    overall_readiness: str
    passed_count: int
    warning_count: int
    error_count: int
    readiness_items: List[ReviewReadinessItem]
    permitted_verification_roles: List[str] = [
        "HUMAN_REVIEWER",
        "LICENSED_SURVEYOR",
        "REVENUE_OFFICIAL"
    ]
    governance_notice: str = (
        "Verification is strictly restricted to authorized human roles. "
        "SYSTEM_VALIDATOR and automated algorithms cannot verify units."
    )


class DossierAIContextSection(BaseModel):
    has_analysis: bool
    advisory_notice: str = (
        "AI-assisted non-authoritative advisory context. AI outputs and heuristic scores "
        "do not constitute statutory verification, cadastral proof, or ownership certainty."
    )
    analysis: Optional[AICandidateAnalysisResponse] = None


class PrototypeTechnicalReviewDossier(BaseModel):
    """
    Consolidated, read-only Technical Review Dossier for a 3D Vertical Cadastral Unit.
    """
    dossier_version: str = "3.6D-PROTOTYPE"
    generated_at: datetime
    prototype_notice: str = (
        "Research Prototype — Not a statutory cadastral record, title certificate, "
        "ownership deed, or official government 3D ULPIN."
    )

    parcel: DossierParcelContext
    building: DossierBuildingContext
    unit_identity: DossierUnitIdentity
    geometry_summary: DossierGeometrySummary
    taxonomy: VerticalTaxonomyClassification
    lifecycle: DossierLifecycleSection
    source_evidence: DossierSourceEvidenceSection
    evidence_fusion: UnitEvidenceFusionResponse
    topology: UnitTopologyReportResponse
    ai_context: DossierAIContextSection
    review_history: List[AuditHistoryItem]
    limitations: List[str]
